import { EnvType, MAConfig } from "@app/types/module.interfaces";
import log from "@app/utils/logger";
import * as fs from "node:fs";
import * as path from "path";
import { Config } from "./config";

export function generateEnvFile(maconfig: MAConfig, config: Config, env: EnvType) {
	const pluginId = `${maconfig.organizationId}__${maconfig.pluginId}__v${maconfig.pluginVersion.replace(/\./g, "_")}`;
	const fileContent = `// This file is GENERATED by buildPlugin.mjs script
import {PluginEnv} from "lib/plugin/PluginEnv"
export const PLUGIN_ENV = new PluginEnv({
    env: "${env}",
    pluginName: "${config.pluginName}",
    pluginId: "${`${pluginId}${env === "dev" ? "_dev" : ""}`}",
    pluginVersion: "${maconfig.pluginVersion}",
    author: "${config.author}"
})
`;
	const filePath = path.join(config.srcPath, "__env.ts");
	fs.writeFileSync(filePath, fileContent, { encoding: `utf8` });
	log.info(`Created ${filePath}`);
}
